-- Migration 0003: league settings (scoring type / categories / point weights) and
-- per-category matchup snapshots.
--
-- usr.leagues holds provider-detected league SETTINGS only. Credentials stay in
-- usr.teams.league_info (unchanged) until the Phase 4 encryption work.

CREATE TABLE IF NOT EXISTS usr.leagues (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider            varchar(16)  NOT NULL CHECK (provider IN ('espn', 'yahoo')),
    provider_league_id  varchar(64)  NOT NULL,
    season              integer      NOT NULL,
    name                varchar(255),
    scoring_type        varchar(16)  NOT NULL DEFAULT 'points'
                                     CHECK (scoring_type IN ('points', 'categories', 'roto')),
    category_win_mode   varchar(16)  CHECK (category_win_mode IN ('each_category', 'most_categories')),
    categories          jsonb        NOT NULL DEFAULT '[]'::jsonb,
    point_weights       jsonb        NOT NULL DEFAULT '{}'::jsonb,
    matchup_periods     jsonb        NOT NULL DEFAULT '{}'::jsonb,
    roster_slots        jsonb        NOT NULL DEFAULT '{}'::jsonb,
    raw_settings        jsonb,
    settings_synced_at  timestamp with time zone,
    created_at          timestamp with time zone NOT NULL DEFAULT now(),
    updated_at          timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT leagues_provider_league_season_uq UNIQUE (provider, provider_league_id, season)
);

ALTER TABLE usr.teams
    ADD COLUMN IF NOT EXISTS league_id integer REFERENCES usr.leagues(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS team_league_id ON usr.teams USING btree (league_id);

ALTER TABLE stats_s2.daily_matchup_scores
    ADD COLUMN IF NOT EXISTS category_scores jsonb;
