-- Migration 0005: encrypted provider credentials.
--
-- ESPN cookies and Yahoo OAuth tokens have lived in plaintext inside
-- usr.teams.league_info since the beginning (0003 called encryption future
-- work). On 2026-08-27 an unauthenticated query endpoint connecting as a
-- superuser could read that column, so the credentials are moving to a
-- dedicated encrypted store.
--
-- One row per (user, provider, provider-side account) rather than per team: a
-- user's ESPN cookies are the same for every league they are in, so the old
-- per-team copies were duplicating the same secret N times.
--
-- The secrets travel as a Fernet-encrypted JSON blob (see core/crypto.py).
-- Non-secret fields -- league_id, team_name, year, scoring_preview -- stay in
-- league_info; only the credentials move.
--
-- This migration is additive. Nothing reads the new table until CREDENTIAL_KEYS
-- is set, and services/credential_service.py falls back to league_info for any
-- team without a connection, so backfill can lag the deploy.

CREATE TABLE IF NOT EXISTS usr.provider_connections (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             integer      NOT NULL REFERENCES usr.users(user_id) ON DELETE CASCADE,
    provider            varchar(16)  NOT NULL CHECK (provider IN ('espn', 'yahoo')),

    -- The provider-side account this credential belongs to, so re-connecting
    -- the same account updates one row instead of accumulating them. ESPN: the
    -- SWID guid. Yahoo: the account guid when known. Empty string rather than
    -- NULL so the unique constraint actually constrains (NULLs are distinct).
    external_account_id varchar(128) NOT NULL DEFAULT '',

    -- Fernet token over a JSON object of that provider's secrets.
    secret_ciphertext   text         NOT NULL,
    key_version         smallint     NOT NULL,

    -- Mirrored in cleartext so "which tokens need refreshing" is a query rather
    -- than a decrypt of every row. NULL for ESPN, whose cookies carry no stated
    -- expiry.
    expires_at          timestamp with time zone,

    created_at          timestamp with time zone NOT NULL DEFAULT now(),
    updated_at          timestamp with time zone NOT NULL DEFAULT now(),
    last_used_at        timestamp with time zone,

    CONSTRAINT provider_connections_user_provider_account_uq
        UNIQUE (user_id, provider, external_account_id)
);

COMMENT ON TABLE usr.provider_connections IS
  'Encrypted third-party credentials. Never expose rows through an API response; see schemas/common.py.';
COMMENT ON COLUMN usr.provider_connections.secret_ciphertext IS
  'Fernet token over a JSON object of provider secrets. Decrypt via core.crypto.';
COMMENT ON COLUMN usr.provider_connections.key_version IS
  'Which CREDENTIAL_KEYS version encrypted this row. A key may only be retired once no row references it.';

CREATE INDEX IF NOT EXISTS provider_connections_user_id
    ON usr.provider_connections USING btree (user_id);

ALTER TABLE usr.teams
    ADD COLUMN IF NOT EXISTS provider_connection_id integer
        REFERENCES usr.provider_connections(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS team_provider_connection_id
    ON usr.teams USING btree (provider_connection_id);
