-- Migration 0010: Draft Lab foundations (usr side).
--
-- usr.leagues gains the typed draft fields parsed from provider settings payloads:
-- position_limits (hard per-position roster caps, e.g. {"C": 4}; unlimited omitted,
-- 0 = none allowed) and draft_settings (type/date/pick order/timer/keepers/auction
-- budget). usr.draft_sessions + usr.draft_picks hold per-user draft-room state; the
-- draft board itself is derived and never stored.

ALTER TABLE usr.leagues
    ADD COLUMN IF NOT EXISTS position_limits jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS draft_settings  jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS usr.draft_sessions (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL REFERENCES usr.users(user_id) ON DELETE CASCADE,
    team_id       integer REFERENCES usr.teams(team_id) ON DELETE SET NULL,
    league_id     integer REFERENCES usr.leagues(id) ON DELETE SET NULL,
    kind          varchar(16) NOT NULL DEFAULT 'manual'
                  CHECK (kind IN ('live', 'manual', 'mock', 'import')),
    status        varchar(16) NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'completed', 'abandoned')),
    draft_type    varchar(16) NOT NULL DEFAULT 'snake'
                  CHECK (draft_type IN ('snake', 'auction')),
    pick_order    jsonb NOT NULL DEFAULT '[]'::jsonb,
    my_slot       integer,
    rounds        integer,
    keepers       jsonb NOT NULL DEFAULT '[]'::jsonb,
    started_at    timestamp with time zone,
    completed_at  timestamp with time zone,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    updated_at    timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS draft_sessions_user_id ON usr.draft_sessions USING btree (user_id);

CREATE TABLE IF NOT EXISTS usr.draft_picks (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      integer NOT NULL REFERENCES usr.draft_sessions(id) ON DELETE CASCADE,
    overall_pick    integer NOT NULL,
    round           integer,
    slot            integer,
    player_id       integer REFERENCES nba.players(id) ON DELETE SET NULL,
    espn_player_id  integer,
    player_name     varchar(255),
    by_me           boolean NOT NULL DEFAULT false,
    source          varchar(16) NOT NULL DEFAULT 'manual'
                    CHECK (source IN ('manual', 'espn_sync', 'import')),
    bid             numeric(7,2),
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT draft_picks_session_overall_uq UNIQUE (session_id, overall_pick)
);

CREATE INDEX IF NOT EXISTS draft_picks_session_id ON usr.draft_picks USING btree (session_id);
