-- Migration 0011: Draft Lab foundations (nba side).
--
-- nba.player_projections: preseason per-game stat projections (source 'espn' now,
-- 'cv' later). nba.draft_market: draft-market snapshots — ESPN's editorial rank and
-- auction value plus the crowd averages from real ESPN drafts (ownership.
-- averageDraftPosition / auctionValueAverage). Snapshots are kept per as_of_date so
-- September rank drift stays queryable. There is no positional rank on the wire;
-- it is derived at read time. Written by the data-platform preseason-market
-- pipeline; backend reads.

CREATE TABLE IF NOT EXISTS nba.player_projections (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id        integer NOT NULL REFERENCES nba.players(id) ON DELETE CASCADE,
    season           character varying(7) NOT NULL,   -- e.g. '2026-27'
    source           varchar(16) NOT NULL DEFAULT 'espn',
    as_of_date       date NOT NULL,
    projected_gp     smallint,
    -- Projected per-game line (same stat vocabulary as nba.player_rolling_stats;
    -- rates recomputed from makes/attempts at read, never stored)
    min              numeric(5,2),
    pts              numeric(5,2),
    reb              numeric(5,2),
    ast              numeric(5,2),
    stl              numeric(5,2),
    blk              numeric(5,2),
    tov              numeric(5,2),
    fgm              numeric(5,2),
    fga              numeric(5,2),
    fg3m             numeric(5,2),
    fg3a             numeric(5,2),
    ftm              numeric(5,2),
    fta              numeric(5,2),
    raw              jsonb,
    pipeline_run_id  uuid,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_projections_natural_uq UNIQUE (player_id, season, source, as_of_date)
);

CREATE INDEX IF NOT EXISTS player_projections_season_asof
    ON nba.player_projections USING btree (season, as_of_date);

CREATE TABLE IF NOT EXISTS nba.draft_market (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id          integer NOT NULL REFERENCES nba.players(id) ON DELETE CASCADE,
    season             character varying(7) NOT NULL,
    source             varchar(16) NOT NULL DEFAULT 'espn',
    as_of_date         date NOT NULL,
    overall_rank       integer,          -- editorial draftRanksByRankType.STANDARD.rank
    auction_value      numeric(6,1),     -- editorial auction value
    adp                numeric(6,2),     -- ownership.averageDraftPosition (real ESPN drafts)
    auction_value_avg  numeric(7,2),     -- ownership.auctionValueAverage
    pipeline_run_id    uuid,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT draft_market_natural_uq UNIQUE (player_id, season, source, as_of_date)
);

CREATE INDEX IF NOT EXISTS draft_market_season_asof
    ON nba.draft_market USING btree (season, as_of_date);
