-- Migration 0020: lineup writes.
--
-- usr.roster_moves is the audit trail of every lineup transaction Court Vision
-- sent (or tried to send) to a provider on a user's behalf — the manual editor
-- and the pre-tip auto-lineup run both write here. The partial unique index is
-- the auto run's dedup: one *counted* attempt (applied / applied_unverified /
-- noop) per team per fantasy day; rejected and failed rows may repeat, so a
-- refused write does not stop a later retry.
--
-- auto_lineup_enabled turns the existing lineup alert into an action: instead
-- of emailing the suggested moves, the pipeline asks the backend to apply them.
-- Global default false; the team-level column is NULL = inherit, like every
-- other override on usr.notification_team_preferences.

CREATE TABLE IF NOT EXISTS usr.roster_moves (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           integer      NOT NULL REFERENCES usr.users(user_id) ON DELETE CASCADE,
    team_id           integer      NOT NULL REFERENCES usr.teams(team_id) ON DELETE CASCADE,
    nba_date          date         NOT NULL,
    scoring_period_id integer,
    source            varchar(10)  NOT NULL CHECK (source IN ('manual', 'auto')),
    status            varchar(20)  NOT NULL
                      CHECK (status IN ('applied', 'applied_unverified', 'rejected', 'failed', 'noop')),
    moves             jsonb        NOT NULL DEFAULT '[]'::jsonb,
    provider_status   integer,
    error             text,
    idempotency_key   varchar(96),
    created_at        timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS roster_moves_team_date ON usr.roster_moves (team_id, nba_date);

CREATE UNIQUE INDEX IF NOT EXISTS roster_moves_auto_once_per_day_uq
    ON usr.roster_moves (team_id, nba_date)
    WHERE source = 'auto' AND status IN ('applied', 'applied_unverified', 'noop');

ALTER TABLE usr.notification_preferences
    ADD COLUMN IF NOT EXISTS auto_lineup_enabled boolean NOT NULL DEFAULT false;

ALTER TABLE usr.notification_team_preferences
    ADD COLUMN IF NOT EXISTS auto_lineup_enabled boolean;
