-- Migration 0028: scheduled pickups.
--
-- usr.scheduled_pickups holds a free-agent add (optionally with a drop) a user
-- asked Court Vision to make for a later ESPN day — the week grid's "pick him
-- up on Thursday". The executor job (POST /v1/internal/jobs/pickups/execute,
-- fired through data-platform's scheduled-pickups pipeline every minute) claims
-- the rows that are due and settles each one: executed, skipped (the player is
-- gone — the no-op), failed (ESPN refused, the connection expired), expired
-- (day D's games started first) or cancelled (the user). A pending row may be
-- attempted more than once: a lock, a waiver period or a writer outage sets
-- next_attempt_at and the row waits; the claim itself is a short lease on the
-- same column, so two overlapping runs never take one row.
--
-- The writes it makes are audited in usr.roster_moves like every other write,
-- under a third source, 'scheduled' — not 'auto', whose partial unique index
-- and daily dedup belong to auto-lineup. 0020 declared the source CHECK inline,
-- so it carries Postgres's default name; 0022 did the same dance for `kind`.

CREATE TABLE IF NOT EXISTS usr.scheduled_pickups (
    id                integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           integer      NOT NULL REFERENCES usr.users(user_id) ON DELETE CASCADE,
    team_id           integer      NOT NULL REFERENCES usr.teams(team_id) ON DELETE CASCADE,
    add_player_id     integer      NOT NULL,                 -- ESPN player id
    drop_player_id    integer,                               -- ESPN player id; NULL = an open seat
    add_name          varchar(120) NOT NULL,                 -- names as the pool / board gave them when scheduled
    add_team          varchar(8),
    drop_name         varchar(120),
    drop_team         varchar(8),
    scoring_period_id integer      NOT NULL,                 -- ESPN day D the pickup is for
    nba_date          date         NOT NULL,                 -- D as a calendar date
    not_before_at     timestamp with time zone NOT NULL,     -- first attempt
    deadline_at       timestamp with time zone,              -- D's first tip-off; NULL = until the day passes
    next_attempt_at   timestamp with time zone,              -- a deferred retry, or the claim lease
    attempts          integer      NOT NULL DEFAULT 0,
    last_attempt_at   timestamp with time zone,
    status            varchar(12)  NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'executed', 'skipped', 'failed', 'cancelled', 'expired')),
    reason            varchar(40),                           -- why it settled or waits
    detail            text,                                  -- ESPN's sentence / the last error
    audit_id          integer REFERENCES usr.roster_moves(id) ON DELETE SET NULL,   -- the add/drop row
    lineup_audit_id   integer REFERENCES usr.roster_moves(id) ON DELETE SET NULL,   -- the seat-on-day-D row
    seated_slot_id    integer,                               -- where he was seated for day D; NULL = bench
    created_at        timestamp with time zone NOT NULL DEFAULT now(),
    updated_at        timestamp with time zone NOT NULL DEFAULT now(),
    executed_at       timestamp with time zone
);

CREATE INDEX IF NOT EXISTS scheduled_pickups_due
    ON usr.scheduled_pickups (not_before_at)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS scheduled_pickups_team
    ON usr.scheduled_pickups (team_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS scheduled_pickups_pending_add_uq
    ON usr.scheduled_pickups (team_id, add_player_id)
    WHERE status = 'pending';

ALTER TABLE usr.roster_moves
    DROP CONSTRAINT IF EXISTS roster_moves_source_check;

ALTER TABLE usr.roster_moves
    ADD CONSTRAINT roster_moves_source_check
    CHECK (source IN ('manual', 'auto', 'scheduled'));
