-- Migration 0029: lineup snapshots.
--
-- usr.lineup_snapshots holds every fantasy team's lineup for each finished ESPN
-- scoring period: which players were rostered that day and the slot each one
-- sat in. The data-platform pipeline `lineup_snapshots` writes it once a night,
-- after ESPN has rolled the period, by reading the league with
-- `?scoringPeriodId=N` — ESPN answers that with the roster AS OF day N
-- (membership and slots), for every team in the league at once. The backend
-- reads it so a past day of a matchup shows the rosters that actually counted
-- instead of today's, with the bench told apart from the starters.
--
-- Rows are keyed by the provider's own ids (league, season, team) rather than
-- usr.teams: opponents have no usr.teams row, and two users in one league share
-- one capture. `season` is the provider's season id (ESPN: 2027 for 2026-27),
-- the same key usr.leagues uses. A re-capture replaces the whole team-day
-- (delete the header, cascade, insert) inside one transaction, so
-- `captured_at` is the row's write time; there is no updated_at.
--
-- nba_player_id is deliberately NOT stored: nba.players.espn_id keeps gaining
-- coverage, and the read path resolves ids at query time.
--
-- The applied totals come from each player's stat line for the period
-- (`player.stats[]` with scoringPeriodId = N, statSplitTypeId 5, statSourceId 0),
-- NOT from `playerPoolEntry.appliedStatTotal` / `roster.appliedStatTotal`, which
-- ESPN fills with the most recent lines in the payload whatever day was asked.

CREATE TABLE IF NOT EXISTS usr.lineup_snapshots (
    id                        integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider                  varchar(16)  NOT NULL CHECK (provider IN ('espn', 'yahoo')),
    provider_league_id        varchar(64)  NOT NULL,          -- ESPN: str(league_id); same key as usr.leagues
    season                    integer      NOT NULL,          -- provider season id (ESPN 2027 = 2026-27)
    provider_team_id          integer      NOT NULL,          -- the team's id inside the league
    team_name                 varchar(120) NOT NULL,
    scoring_period_id         integer      NOT NULL,          -- ESPN day (1 = opening night)
    nba_date                  date         NOT NULL,          -- that day as a calendar date
    matchup_period_id         integer,                        -- the matchup week the day belongs to (best effort)
    opponent_provider_team_id integer,                        -- the opponent that week (best effort)
    applied_stat_total        numeric(8,2),                   -- the day's points over the active slots, from ESPN's per-player day lines
    player_count              smallint     NOT NULL,
    source                    varchar(16)  NOT NULL DEFAULT 'pipeline'
                              CHECK (source IN ('pipeline', 'backfill')),
    captured_at               timestamp with time zone NOT NULL DEFAULT now(),
    pipeline_run_id           uuid,
    CONSTRAINT lineup_snapshots_team_period_uq
        UNIQUE (provider, provider_league_id, season, provider_team_id, scoring_period_id)
);

CREATE INDEX IF NOT EXISTS lineup_snapshots_league_date
    ON usr.lineup_snapshots (provider, provider_league_id, season, nba_date);

CREATE TABLE IF NOT EXISTS usr.lineup_snapshot_players (
    id                   integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id          integer      NOT NULL REFERENCES usr.lineup_snapshots(id) ON DELETE CASCADE,
    player_id            integer      NOT NULL,               -- the provider's player id (ESPN)
    player_name          varchar(120) NOT NULL,
    pro_team             varchar(8),                          -- NBA team abbreviation; NULL/FA when unsigned
    default_position_id  smallint,
    lineup_slot_id       smallint     NOT NULL,               -- ESPN slot ids: 0 PG ... 11 UT, 12 BE, 13 IR
    eligible_slot_ids    jsonb,                               -- [int]; as nba.draft_market.eligible_slot_ids
    injured              boolean      NOT NULL DEFAULT false,
    injury_status        varchar(24),
    applied_total        numeric(8,2),                        -- ESPN's points for him that day (his stat line for the period); NULL = no game
    CONSTRAINT lineup_snapshot_players_uq UNIQUE (snapshot_id, player_id)
);
